FROM basi/prometheus-swarm:latest
ADD alert.rules_nodes /etc/prometheus/alert.rules_nodes
ADD prometheus.yml /etc/prometheus/prometheus.yml
ADD alert.rules_service-groups /etc/prometheus/alert.rules_service-groups
ADD alert.rules_tasks /etc/prometheus/alert.rules_tasks
